config/routes.rb
Rails.application.routes.draw do

  get 'orders/destroy'

  get 'hoods/show'

  resources :order_items
 
  get 'menu_items/:id/restaurant' => 'menu_items#show', as: :menu
  get 'neighborhood/:id' => 'hoods#show', as: :hood
  
  
  seems_rateable
  resources :sellers
  resources :cities
  devise_for :users
  get 'welcome/home'
  

  root 'welcome#home'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
      #if user.email == "ericmwenda5@gmail.com" # you can add any condition
       # can :manage, :all
      #end
    # can :access, :rails_admin   # grant access to rails_admin
    # can :dashboard   
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.role == "admin"
        can :manage, :all
      else
        can :manage, :all
      end
    
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :menu_items
	belongs_to :seller
end

app/models/city.rb
class City < ActiveRecord::Base
    has_many :hoods
end

app/models/hood.rb
class Hood < ActiveRecord::Base
    belongs_to :city
    has_many :sellers
end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
	belongs_to :seller
	validates :seller, presence: :true

	belongs_to :category
	validates :category, presence: :true
	
	has_many :order_items
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
	has_many :order_items, dependent: :destroy
	
	def total
		total=0
		  self.order_items.each{|item| total+=item.subtotal}
		  total
	end 
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
	belongs_to :order
    belongs_to :menu_item
    validates :order_id, :menu_item_id, presence: true
    validates :quantity, numericality: {greater_than_or_equal_to: 1, only_integer: true}
     def subtotal
    	self.quantity * self.menu_item.price
    end
end

app/models/seller.rb
class Seller < ActiveRecord::Base
     seems_rateable :stars# :speed, :effectiveness
	 belongs_to :hood
	 has_many :menu_items
	 has_many :categories
	 validates :opening_time,:closing_time, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	seems_rateable_rater
	has_many :orders
	ROLES = %i[admin seller banned]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         	:recoverable, :rememberable, :confirmable, :trackable, :validatable
         	
         	
    rails_admin do
      list do
        field :email
        field :created_at
        field :sign_in_count
        field :last_sign_in_at
        field :fname
        field :lname
        field :role
     
      end
      
      edit do
        field :fname
        field :lname
        field :email
        field :password
        field :password_confirmation
        field :role
      end
    end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
    def create
      @hood=Hood.find(params[:id])
      @sellers=@hood.sellers
      render partial: 'hoods/search'
    end
    
  def show
   @hood=Hood.find(params[:id])
   @sellers=@hood.sellers
   render :show
  end

  def new

  end

  def edit
  end

  def update
  end

  def delete
  end
end

app/controllers/city_controller.rb
class CitiesController < ApplicationController
  def show
   @hood=Hood.find(params[:id])
   @sellers=@hood.sellers
   render :show
  end

  def new

  end

  def edit
  end

  def update
  end

  def delete
  end
end

app/controllers/hoods_controller.rb
class HoodsController < ApplicationController
  def show
     @hood=Hood.find(params[:id])
     @sellers=@hood.sellers
     render :show
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def destroy
    Order.find(session[:order_id]).delete
    reset_session
    redirect_to request.referrer
  end
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  before_action :set_seller, only: [:show, :edit, :update, :destroy]

  # GET /sellers
  # GET /sellers.json
  def index
    @sellers = Seller.all
  end

  # GET /sellers/1
  # GET /sellers/1.json
  def show
  end

  # GET /sellers/new
  def new
    @seller = Seller.new
  end

  # GET /sellers/1/edit
  def edit
  end

  # POST /sellers
  # POST /sellers.json
  def create
    @seller = Seller.new(seller_params)

    respond_to do |format|
      if @seller.save
        format.html { redirect_to @seller, notice: 'Seller was successfully created.' }
        format.json { render :show, status: :created, location: @seller }
      else
        format.html { render :new }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sellers/1
  # PATCH/PUT /sellers/1.json
  def update
    respond_to do |format|
      if @seller.update(seller_params)
        format.html { redirect_to @seller, notice: 'Seller was successfully updated.' }
        format.json { render :show, status: :ok, location: @seller }
      else
        format.html { render :edit }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sellers/1
  # DELETE /sellers/1.json
  def destroy
    @seller.destroy
    respond_to do |format|
      format.html { redirect_to sellers_url, notice: 'Seller was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seller
      @seller = Seller.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seller_params
      params.require(:seller).permit(:name, :image_url, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
    @cities=City.all
    @sellers=Seller.take(10)
    @grouped_options =@cities.collect{|city|
                                    [city.name, 
                                    city.hoods.collect{|h| 
                                    [h.name,h.id]
                                    }]}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def print_price(price)
    number_to_currency(price, unit: "Ksh ")
  end
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/hoods_helper.rb
module HoodsHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/hoods/_search.html.haml
%section
  .container
    / page header
    #location.page-header
      %h1
        Restaurants in 
        %span.text-danger 
          =@hood.name
    / EOf page heade
    / page grids
    .row
      / left col
      .col-sm-3.col-md-3
        =render partial: "shared/locations"
      / Eof left-col
      / middle col
      #content.col-lg-6
        / <p id="notice"><haml_loud> notice </haml_loud></p>
        = render partial: "shared/show_sellers", locals: {sellers: @sellers}
      / eof middle-col
      / right col
      .col-lg-3
        = render partial: "shared/side"
    / eof grid
  / Eof container

app/views/hoods/show.html.haml
.breadcrumb
  .container
    =fa_icon 'home' 
    =link_to "Home", root_url
    =fa_icon "chevron-right"
    =link_to @hood.name, hood_url(@hood.id)
%section
  .container
    / page header
    #location.page-header
      %h1
        Restaurants in 
        %span.text-danger 
          =@hood.name
    / EOf page heade
    / page grids
    .row
      / left col
      .col-sm-3.col-md-3
        =render partial: "shared/locations"
      / Eof left-col
      / middle col
      #content.col-lg-6
        / <p id="notice"><haml_loud> notice </haml_loud></p>
        = render partial: "shared/show_sellers", locals: {sellers: @sellers}
      / eof middle-col
      / right col
      .col-lg-3
        = render partial: "shared/side"
    / eof grid
  / Eof container

app/views/orders/destroy.html.erb
<h1>Orders#destroy</h1>
<p>Find me in app/views/orders/destroy.html.erb</p>

app/views/sellers/_form.html.haml
= form_for(@seller) do |f|
  - if @seller.errors.any?
    #error_explanation
      %h2
        = pluralize(@seller.errors.count, "error")
        prohibited this seller from being saved:
      %ul
        - @seller.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :image_url
    %br/
    = f.text_field :image_url
  .field
    = f.label :description
    %br/
    = f.text_area :description
  .actions
    = f.submit

app/views/sellers/edit.html.haml
%h1 Editing Seller
= render 'form'
= link_to 'Show', @seller
|
= link_to 'Back', sellers_path

app/views/sellers/index.html.haml
%section
  .container
    / page header
    #location.page-header
      %h1
        Popular Restaurants 
    / EOf page heade
    / page grids
    .row
      / left col
      .col-sm-3.col-md-3
        =render partial: "shared/locations"
      / Eof left-col
      / middle col
      #content.col-lg-6
        / <p id="notice"><haml_loud> notice </haml_loud></p>
        = render partial: "shared/show_sellers", locals: {sellers: @sellers}
      / eof middle-col
      / right col
      .col-lg-3
        / panel order
        .panel.panel-primary
          .panel-heading
            Current Order
          .panel-body
            NO ITEMS IN YOUR ORDER
        / panel contacts
        .panel.panel-danger
          .panel-heading
            Need Help?
          .panel-body
            %p call to order
            %h3
              = fa_icon "phone"
              0729956363
      / EOF right-col
    / eof grid
  / Eof container

app/views/sellers/new.html.haml
%h1 New Seller
= render 'form'
= link_to 'Back', sellers_path

app/views/sellers/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @seller.name
%p
  %strong Image url:
  = @seller.image_url
%p
  %strong Description:
  = @seller.description
= link_to 'Edit', edit_seller_path(@seller)
|
= link_to 'Back', sellers_path