config/routes.rb
Rails.application.routes.draw do

  get 'orders/destroy'

  get 'hoods/show'

  resources :order_items
 
  get 'menu_items/:id/restaurant' => 'menu_items#show', as: :menu
  get 'neighborhood/:id' => 'hoods#show', as: :hood
  
  
  seems_rateable
  resources :sellers
  resources :cities
  devise_for :users
  get 'welcome/home'
  

  root 'welcome#home'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
      #if user.email == "ericmwenda5@gmail.com" # you can add any condition
       # can :manage, :all
      #end
    # can :access, :rails_admin   # grant access to rails_admin
    # can :dashboard   
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.role == "admin"
        can :manage, :all
      else
        can :manage, :all
      end
    
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :menu_items
	belongs_to :seller
end

app/models/city.rb
class City < ActiveRecord::Base
    has_many :hoods
end

app/models/hood.rb
class Hood < ActiveRecord::Base
    belongs_to :city
    has_many :sellers
end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
	belongs_to :seller
	validates :seller, presence: :true

	belongs_to :category
	validates :category, presence: :true
	
	has_many :order_items
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
	has_many :order_items, dependent: :destroy
	
	def total
		total=0
		  self.order_items.each{|item| total+=item.subtotal}
		  total
	end 
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
	belongs_to :order
    belongs_to :menu_item
    validates :order_id, :menu_item_id, presence: true
    validates :quantity, numericality: {greater_than_or_equal_to: 1, only_integer: true}
     def subtotal
    	self.quantity * self.menu_item.price
    end
end

app/models/seller.rb
class Seller < ActiveRecord::Base
     seems_rateable :stars# :speed, :effectiveness
	 belongs_to :hood
	 has_many :menu_items
	 has_many :categories
	 validates :opening_time,:closing_time, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	seems_rateable_rater
	has_many :orders
	ROLES = %i[admin seller banned]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         	:recoverable, :rememberable, :confirmable, :trackable, :validatable
         	
         	
    rails_admin do
      list do
        field :email
        field :created_at
        field :sign_in_count
        field :last_sign_in_at
        field :fname
        field :lname
        field :role
     
      end
      
      edit do
        field :fname
        field :lname
        field :email
        field :password
        field :password_confirmation
        field :role
      end
    end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
    def create
      @hood=Hood.find(params[:id])
      @sellers=@hood.sellers
      render partial: 'hoods/search'
    end
    
  def show
   @hood=Hood.find(params[:id])
   @sellers=@hood.sellers
   render :show
  end

  def new

  end

  def edit
  end

  def update
  end

  def delete
  end
end

app/controllers/city_controller.rb
class CitiesController < ApplicationController
  def show
   @hood=Hood.find(params[:id])
   @sellers=@hood.sellers
   render :show
  end

  def new

  end

  def edit
  end

  def update
  end

  def delete
  end
end

app/controllers/hoods_controller.rb
class HoodsController < ApplicationController
  def show
     @hood=Hood.find(params[:id])
     @sellers=@hood.sellers
     render :show
  end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  def show
  	@seller=Seller.find(params[:id])
  	@categories=@seller.categories
  #	@items=
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def destroy
    Order.find(session[:order_id]).delete
    reset_session
    redirect_to request.referrer
  end
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  before_action :set_seller, only: [:show, :edit, :update, :destroy]

  # GET /sellers
  # GET /sellers.json
  def index
    @sellers = Seller.all
  end

  # GET /sellers/1
  # GET /sellers/1.json
  def show
  end

  # GET /sellers/new
  def new
    @seller = Seller.new
  end

  # GET /sellers/1/edit
  def edit
  end

  # POST /sellers
  # POST /sellers.json
  def create
    @seller = Seller.new(seller_params)

    respond_to do |format|
      if @seller.save
        format.html { redirect_to @seller, notice: 'Seller was successfully created.' }
        format.json { render :show, status: :created, location: @seller }
      else
        format.html { render :new }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sellers/1
  # PATCH/PUT /sellers/1.json
  def update
    respond_to do |format|
      if @seller.update(seller_params)
        format.html { redirect_to @seller, notice: 'Seller was successfully updated.' }
        format.json { render :show, status: :ok, location: @seller }
      else
        format.html { render :edit }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sellers/1
  # DELETE /sellers/1.json
  def destroy
    @seller.destroy
    respond_to do |format|
      format.html { redirect_to sellers_url, notice: 'Seller was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seller
      @seller = Seller.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seller_params
      params.require(:seller).permit(:name, :image_url, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def print_price(price)
    number_to_currency(price, unit: "Ksh ")
  end
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/hoods_helper.rb
module HoodsHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/menu_items/show.html.erb
<div class="breadcrumb">
  <div class="container">
    <a href=""><%= fa_icon 'home'%> Home </a>>
    <a href=""><%=link_to @seller.hood.name, hood_url(@seller.hood.id) %> </a>>
    <a href=""><%=link_to @seller.name, menu_url(@seller)%> </a>

  </div>
</div>
<div class="restaurant-banner hidden-xs hidden-sm">
    <div class="container">
       <div class="row restaurant-banner-info">
           
            <div class="col-md-4 the-rest-info">
               <h3><%=  @seller.name %></h3>
               <div class="restaurant-rating">
                   <span class="text-danger">Rating</span>
                 
                 <%= rating_for @seller %>
                </div>
                <div>
                    <b class="text-danger">Opening Hours</b></br>
                     <i class="fa fa-clock-o">
                       <%= @seller.opening_time.to_formatted_s(:time) %> - <%= @seller.closing_time.to_formatted_s(:time) %> &nbsp
                   </i>
                </div>
                <b class="text-danger">Info</b></br>
                 <span class="info food-type"><%= @seller.description %></span>
            </div>
            
           <div class="col-md-2 rest-banner-cash">
               <h4>
                   <i class="fa fa-clock-o">
                       <%= @seller.opening_time.to_formatted_s(:time) %> - <%= @seller.closing_time.to_formatted_s(:time) %> &nbsp
                   </i>
               </h4>
            </div>
            
            <div class="col-md-2 rest-banner-status">
                <h3>
                    <% if (@seller.opening_time.to_formatted_s(:time).to_i .. @seller.closing_time.to_formatted_s(:time).to_i).include?(Time.now.in_time_zone("Nairobi").to_formatted_s(:time).to_i) %>
                    <span class="label label-success">Open</span>
                    <%else%>
                    <span class="label label-danger">Closed</span>
                    <%end%>
                </h3>
            </div>
            
           <div class="col-md-4 restaurant-banner-image">
               <%= image_tag(@seller.image_url, alt: @seller.name, class: "img-responsive img-circle") %>
            </div>
        </div> 
    </div>
</div>

<div class="container">
    <div id="page-content" class="row">
        <div class="col-sm-8">
            <div class="row card">
                    <div class="col-md-3 hidden-xs hidden-sm">
                        <h3><%= fa_icon "coffee" %> Cuisines</h3>
                        <ul>
                            <% @categories.each do |category| %>
                            <li>
                                <%=fa_icon 'caret-right'%>
                                <%= link_to category.name, '#cat'+category.id.to_s %></li>
                            <% end %>
                        </ul>
                    </div>
                    <div class="col-md-9">
                        <%if @categories.empty?%>
                        <div class="alert alert-info">No updated menu for this restaurant </div>
                        <% end%>
                        <% @categories.each do |category|%>
                           <div id="cat<% category.id.to_s%>" class="panel panel-default noborder">
                              <div class="panel-heading">
                                <h3><%= category.name %></h3>
                            </div>
                            <div class="panel-body">
                            <ul class="food-menu">
                                <!--EOF item category  -->
                            <% category.menu_items.each do |menu| %>
                                <li>
                                  <div class="item">
                                    <div class="col-sm-4 col-xm-3">
                                      <%= image_tag(menu.image_url, alt: menu.name, class: "menu_item_img") %>
                                    </div>
                                    <div class="container-fluid">
                                            <p class="name text-capitalize"><%= menu.name %></p>
                                            <p class="info"><%= menu.description %></p>
                                    </div>
                                    <div class="pull-right">
                                        <span class="pricenr"><%= print_price(menu.price)%></span>
                                        <div class="actions">
                                              
                                        <%=button_to "Buy", order_items_path(menu_id: menu.id),class: "btn btn-info" %>
                                        </div>
                                    </div>
                                  </div>
                                </li>
                            <% end %>
                               </ul>
                            </div>
                            </div>
                             <!--panel body{dispaly menu items-->
                        <%end%>
                        </div>
                    </div>
                    
            </div>
        <div class="col-sm-4">
            <div class="panel inner-box-content panel-danger">
                <div class="panel-heading">Current Order
                <%= link_to "Empty Cart", orders_destroy_path, class: "pull-right"%>
                </div>
                
                <div class="panel-body basket">
                <!-- shopping list -->
                    <ul class="basketList"> 
                    <!-- shopping item -->
                  
                    <!--loop through order to display order items-->
                    <% order_items.each do |order_item|%>
                        <li class="basketItemRow">
                            <div class="item">
                                <div class="msg">
                                <!-- action buttons -->
                                    <span class="actions"> 
                                        <span class="price"><%=print_price(order_item.subtotal)%></span>
                                        <!-- button add -->
                                        <a data-id="<%=order_item.menu_item_id%>" data-action="add" class="button yum add">
                                            <span class="fa-stack">
                                                <i class="fa fa-circle-o fa-stack-2x"></i>
                                                <i class="fa fa-plus fa-stack-1x"></i>
                                            </span>
                                        </a>
                                        <!-- button minus -->
                                        <a data-id="<%=order_item.menu_item_id%>" data-action="minus"  class="button yum minus">
                                            <span class="fa-stack">
                                                <i class="fa fa-circle-o fa-stack-2x"></i>
                                                <i class="fa fa-minus fa-stack-1x"></i>
                                            </span>
                                        </a>
                                    </span>
                                    <span class="quantity"><%=order_item.quantity%></span>
                                    <span class="xer"> x </span>
                                    <span class="name"><%=order_item.menu_item.name%></span>
                                </div>
                            </div>
                        </li>
                     <%end%>
                        <!--totals-->
                        <li class="total">
                            <div class="item">
                                <div class="msg">
                                    <span class="actions">
                                        <span class="price">
                                            <span class="totalPrice"><%= print_price(cart_total) %></span>
                                        </span>
                                    </span> 
                                    <span class="name">Total:</span>
                                </div>
                             </div>
                        </li>
                    </ul>
                    <a class="btn btn-success">Checkout <%= fa_icon "long-arrow-right" %></a>
                </div>
            </div>
        </div>
    </div>
  </div>
</div>

app/views/menu_items/show.html.haml
.restaurant-banner.hidden-xs.hidden-sm
  .container
    .row.restaurant-banner-info
      .col-md-4.the-rest-info
        %h3= @seller.name
        .restaurant-rating
          %span Rating
          3.3
          \#{rating_for @seller}
        %div
          %span Opening Hours
          %i.fa.fa-clock-o
            = @seller.opening_time.to_formatted_s(:time)
            \- #{@seller.closing_time.to_formatted_s(:time)} &amp;nbsp
        %span.info.food-type= @seller.description
      .col-md-2.rest-banner-cash
        %h4
          %i.fa.fa-clock-o
            = @seller.opening_time.to_formatted_s(:time)
            \- #{@seller.closing_time.to_formatted_s(:time)} &amp;nbsp
      .col-md-2.rest-banner-status
        %h3
          //calculate range between opening time and closing time. then check if curent time is in that range if yes ? open : closed
          - if (@seller.opening_time.to_formatted_s(:time).to_i .. @seller.closing_time.to_formatted_s(:time).to_i).include?(Time.now.in_time_zone("Nairobi").to_formatted_s(:time).to_i)
            %span.label.label-success Open
          - else
            %span.label.label-danger Closed
      .col-md-4.restaurant-banner-image
        = image_tag(@seller.image_url, alt: @seller.name, class: "img-responsive img-circle")
.container
  #page-content.row
    .col-sm-8
      .row.card
        .col-md-3.hidden-xs.hidden-sm
          %h3
            = fa_icon "coffee"
            Cuisines
          %ul
            - @categories.each do |category|
              %li
                = fa_icon 'caret-right'
                = link_to category.name, '#cat'+category.id.to_s
        .col-md-9
          - if @categories.empty?
            .alert.alert-info No updated menu for this restaurant
          - @categories.each do |category|
            .panel.panel-default.noborder{:id => "cat category.id.to_s"}
              .panel-heading
                %h3= category.name
              .panel-body
                %ul.food-menu
                  / EOF item category
                  - category.menu_items.each do |menu|
                    %li
                      .col-sm-4.col-xm-3
                        = image_tag(menu.image_url, alt: menu.name, class: "menu_item_img")
                      .container-fluid
                        %p.name= menu.name
                        %p.info= menu.description
                      .pull-right
                        %span.pricenr= menu.price
                        .actions
                          = link_to fa_icon("plus"), order_items_path(menu_id: menu.id),class: "btn btn-info"
                    %hr/
            / panel body{dispaly menu items
    .col-sm-4
      .panel.inner-box-content.panel-danger
        .panel-heading Current Order
        .panel-body.basket
          / shopping list
          %ul.basketList
            / shopping item
            %li.basketItemRow
              .item
                .msg
                  / action buttons
                  %span.actions
                    %span.price Ksh 50
                    / button add
                    %a.button.yum.add
                      %span.fa-stack
                        %i.fa.fa-circle-o.fa-stack-2x
                        %i.fa.fa-plus.fa-stack-1x
                    / button minus
                    %a.button.yum.minus
                      %span.fa-stack
                        %i.fa.fa-circle-o.fa-stack-2x
                        %i.fa.fa-minus.fa-stack-1x
                  %span.quantity 1
                  %span.xer x
                  %span.name Cheesy Chips
            / totals
            %li.total
              .item
                .msg
                  %span.actions
                    %span.price
                      %span.totalPrice 0 KSh
                  %span.name Total:
          %a.btn.btn-success
            Checkout #{fa_icon "long-arrow-right"}

app/views/menu_items/show.js.haml
$('#ajax-content').html('#{j(render partial: "shared/menu_item", locals: {items: @items})}');