config/routes.rb
Rails.application.routes.draw do

  get 'orders/destroy'

  get 'hoods/show'

  resources :order_items
 
  get 'menu_items/:id/restaurant' => 'menu_items#show', as: :menu
  get 'neighborhood/:id' => 'hoods#show', as: :hood
  
  
  seems_rateable
  resources :sellers
  resources :cities
  devise_for :users
  get 'welcome/home'
  

  root 'welcome#home'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
      #if user.email == "ericmwenda5@gmail.com" # you can add any condition
       # can :manage, :all
      #end
    # can :access, :rails_admin   # grant access to rails_admin
    # can :dashboard   
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.role == "admin"
        can :manage, :all
      else
        can :manage, :all
      end
    
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :menu_items
	belongs_to :seller
end

app/models/city.rb
class City < ActiveRecord::Base
    has_many :hoods
end

app/models/hood.rb
class Hood < ActiveRecord::Base
    belongs_to :city
    has_many :sellers
end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
	belongs_to :seller
	validates :seller, presence: :true

	belongs_to :category
	validates :category, presence: :true
	
	has_many :order_items
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
	has_many :order_items, dependent: :destroy
	
	def total
		total=0
		  self.order_items.each{|item| total+=item.subtotal}
		  total
	end 
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
	belongs_to :order
    belongs_to :menu_item
    validates :order_id, :menu_item_id, presence: true
    validates :quantity, numericality: {greater_than_or_equal_to: 1, only_integer: true}
     def subtotal
    	self.quantity * self.menu_item.price
    end
end

app/models/seller.rb
class Seller < ActiveRecord::Base
     seems_rateable :stars# :speed, :effectiveness
	 belongs_to :hood
	 has_many :menu_items
	 has_many :categories
	 validates :opening_time,:closing_time, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	seems_rateable_rater
	has_many :orders
	ROLES = %i[admin seller banned]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         	:recoverable, :rememberable, :confirmable, :trackable, :validatable
         	
         	
    rails_admin do
      list do
        field :email
        field :created_at
        field :sign_in_count
        field :last_sign_in_at
        field :fname
        field :lname
        field :role
     
      end
      
      edit do
        field :fname
        field :lname
        field :email
        field :password
        field :password_confirmation
        field :role
      end
    end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
    def create
      @hood=Hood.find(params[:id])
      @sellers=@hood.sellers
      render partial: 'hoods/search'
    end
    
  def show
   @hood=Hood.find(params[:id])
   @sellers=@hood.sellers
   render :show
  end

  def new

  end

  def edit
  end

  def update
  end

  def delete
  end
end

app/controllers/city_controller.rb
class CitiesController < ApplicationController
  def show
   @hood=Hood.find(params[:id])
   @sellers=@hood.sellers
   render :show
  end

  def new

  end

  def edit
  end

  def update
  end

  def delete
  end
end

app/controllers/hoods_controller.rb
class HoodsController < ApplicationController
  def show
     @hood=Hood.find(params[:id])
     @sellers=@hood.sellers
     render :show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def print_price(price)
    number_to_currency(price, unit: "Ksh ")
  end
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/hoods_helper.rb
module HoodsHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= controller.action_name
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %link{:href => "https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Roboto:100,200,300,400,500,600,700|Roboto+Condensed:300,400,700", :rel => "stylesheet", :type => "text/css"}/
  %body
    / navigation bar
    %nav.navbar.navbar-default
      .container
        / group  Brand and toggle for better mobiledisplay
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#yum-header", "data-toggle" => "collapse"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          .navbar-brand YUM REPLICATED
        / EOF navbar header
        / Collect the nav links, forms, and other content for toggling
        #yum-header.collapse.navbar-collapse
          %form.navbar-form.navbar-right
            .left-inner-addon
              = fa_icon "search"
              %input.form-control{:placeholder => "Search for a restaurant, cuisine or dish", :type => "text"}
          %ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              %li= link_to('Home', welcome_home_url)
              %li= link_to('Update Profile', edit_user_registration_path)
              %li= link_to('Logout', destroy_user_session_path, :method => :delete)
            - else
              %li= link_to('Home', welcome_home_url)
              %li= link_to('Signup', new_user_registration_path)
              %li= link_to('Login', new_user_session_path)
      / EOF container
    / EOF nav
    #ajax-content
      = yield
    / welcome section
    / footer
  

app/views/locations/show.html.erb
<h1>Location#index</h1>
<p>Find me in app/views/location/index.html.erb</p>
<% @sellers.each do |seller| %>
  <div class="well well-lg">
    <div class="row">
      <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
        <%= image_tag(seller.image_url,alt: seller.name,class: "img-responsive") %>
      </div>
      <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9">
        <h5><%= link_to seller.name %></h5>
        <a class="btn btn-danger pull-right">View menu</a>
        <p><%= seller.description %></p>
        <p>Rating:
        <%= fa_icon "star" %>
        <%= rating_for seller%></p>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_locations.html.haml
#accordion.panel-group.card
  - cities.each do |city|
    .panel.panel-default
      .panel-heading
        %h4.panel-title
          = fa_icon "globe"
          %a{"data-parent" => "#accordion", "data-toggle" => "collapse", :href => "##{city.name+city.id.to_s}"}
            = city.name
      .panel-collapse.collapse{:id => "#{city.name+city.id.to_s}"}
        #panel.panel-body
          %table.table
            - city.hoods.each do|hood|
              %tr
                %td
                  = fa_icon "map-marker"
                  = link_to hood.name, hood_url(hood.id)

app/views/shared/_menu_item.html.haml
.restaurant-banner.hidden-xs.hidden-sm
  .container
    .row.restaurant-banner-info
      .col-md-4.the-rest-info
        %h3= @seller.name
        .restaurant-rating
          %span Rating
          3.3
          \#{rating_for @seller}
        %div
          %span Opening Hours
        %span.info.food-type= @seller.description
      .col-md-2.rest-banner-cash
        %h4
          %i.fa.fa-clock-o 8 Am - 9 Pm
      .col-md-2.rest-banner-status
        %h3
          %span.label.label-success Open
      .col-md-4.restaurant-banner-image
        = image_tag(@seller.image_url, alt: @seller.name, class: "img-responsive img-circle")

app/views/shared/_show_sellers.html.haml
- if !sellers.empty?
  .card
    - sellers.each do |seller|
      .well.well-lg
        .row
          .col-xs-3.col-sm-3.col-md-3.col-lg-3
            = image_tag(seller.image_url,alt: seller.name,class: "img-responsive")
          .col-xs-9.col-sm-9.col-md-9.col-lg-9
            %h5= link_to "#{seller.name}",menu_url(seller)
            = link_to "View Menu",menu_url(seller), class: "btn btn-danger pull-right"
            %p= seller.description
            %p
              Rating:
              \#{fa_icon "star"}
              \#{rating_for seller}
- else
  .alert.alert-danger
    %p
      No Restaurants in this Neighborhood 
      %b.text-uppercase.text-primary
        #{@hood.name}

app/views/shared/_side.html.haml
/ panel order
.panel.panel-primary
  .panel-heading
    Order your Favorite dish online
  .panel-body
/ panel contacts
.panel.panel-danger
  .panel-heading
    Need Help?
  .panel-body
    %p call to order
    %h3
      = fa_icon "phone"
      0729956363
/ EOF right-col